# Generated by Django 4.2.5 on 2023-09-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(default='Item', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='mana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.IntegerField(default=0),
        ),
    ]
